# Generated by Django 4.1.3 on 2022-11-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uspdate', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='accounts.staff')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_delete': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='category.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
