# Generated by Django 4.1.3 on 2022-11-17 13:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uspdate', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('location', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('CONFIRMED', 'confirmed'), ('CANCELLED', 'cancelled'), ('SUCCESS', 'success')], default='new', max_length=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uspdate', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('count', models.PositiveIntegerField()),
                ('bread_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breadss', to='bakery.breaditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
